### ISSUE TITLE
Raising `rasterio.errors.EnvError`

### ISSUE THREAD

**Issue by jacquestardie** [mapbox/supermercado#12]
Attempting to grab the ZXY's of [this geojson](https://gist.github.com/jacquestardie/0d30a002cd3c7d68a7ca1d0d86e4b7ef) with:
```
cat nairobi-final.geojson | supermercado burn 10
```

Which returns:
```
Traceback (most recent call last):
  File "/Users/jacquesbox/.virtualenvs/mapbox27/bin/supermercado", line 11, in <module>
    sys.exit(cli())
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/supermercado/scripts/cli.py", line 58, in burn
    tiles = burntiles.burn(features, zoom)
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/supermercado/burntiles.py", line 63, in burn
    all_touched=True)
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/rasterio/features.py", line 305, in rasterize
    rasterio.env.setenv()
  File "/Users/jacquesbox/.virtualenvs/mapbox27/lib/python2.7/site-packages/rasterio/env.py", line 175, in setenv
    raise EnvError("No environment exists")
rasterio.errors.EnvError: No environment exists
```

I'm working in a virtualenv with the following installs:
```
(mapbox27) ❯ pip freeze | grep supermercado && pip freeze | grep rasterio
supermercado==0.0.2
rasterio==0.35.0.post1
```

I see [references](https://github.com/mapbox/rasterio/blob/db4806469c9b2ecc90c322d790a931e3100c7da0/rasterio/env.py#L89-L91) to EnvError in Rasterio, but am not sure what the fix here would be or how to proceed.

cc @perrygeo

**Comment by perrygeo** [comment]
@jacquestardie confirmed the error on 0.35.0-post1. Maybe try rasterio `0.35.1`? On OSX you might need to upgrade pip to get the wheels.

```
pip install -U pip
pip install -U rasterio
```

these venvs works for me on osx
```
$ pip freeze | grep supermercado && pip freeze | grep rasterio
supermercado==0.0.2
rasterio==0.35.1
$ curl https://gist.githubusercontent.com/jacquestardie/0d30a002cd3c7d68a7ca1d0d86e4b7ef/raw/0868d4bd361a5e231575e507c680ac382c40d600/hot-nairobi.geojson | supermercado burn 10

[617, 514, 10]
[616, 515, 10]
[617, 515, 10]
[616, 516, 10]
[617, 516, 10]

```

and dev versions

```
$ pip freeze | grep supermercado && pip freeze | grep rasterio
-e git+git@github.com:mapbox/supermercado.git@4b1911f5190195ac2190c44abcd5dbe586484b6b#egg=supermercado
-e git+git@github.com:mapbox/rasterio.git@048b33b80c9a11bf11dd72a385e16152dc1ec48b#egg=rasterio
$ curl https://gist.githubusercontent.com/jacquestardie/0d30a002cd3c7d68a7ca1d0d86e4b7ef/raw/0868d4bd361a5e231575e507c680ac382c40d600/hot-nairobi.geojson | supermercado burn 10

[617, 514, 10]
[616, 515, 10]
[617, 515, 10]
[616, 516, 10]
[617, 516, 10]
```

**Comment by sgillies** [comment]
@jacquestardie: @perrygeo is right, 0.35.1 has the fix.

**Comment by jacquestardie** [comment]
Upgrading worked — thank you both!
