### ISSUE TITLE
error for point or linestring

### ISSUE THREAD

**Issue by guyanf** [mapbox/supermercado#29]
When the geojson type is point or linestring, didn't continue.

cat poi.geojson | supermercado burn 18

Traceback (most recent call last):
  File "/usr/local/bin/supermercado", line 11, in <module>
    load_entry_point('supermercado==0.0.5', 'console_scripts', 'supermercado')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/supermercado/scripts/cli.py", line 58, in burn
    tiles = burntiles.burn(features, zoom)
  File "/usr/local/lib/python3.6/dist-packages/supermercado/burntiles.py", line 54, in burn
    bounds = find_extrema(polys)
  File "/usr/local/lib/python3.6/dist-packages/supermercado/burntiles.py", line 22, in find_extrema
    xMax = totalArr[:, 0].max() - epsilon
IndexError: too many indices for array

**Comment by pratikyadav** [comment]
Resolved via https://github.com/mapbox/supermercado/pull/34
Please install the latest build.
