### ISSUE TITLE
fails to install using python3.8

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/supermercado#42]
```
Collecting supermercado==0.1.0
  Downloading supermercado-0.1.0.tar.gz (7.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /var/lang/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11_2o5rv/supermercado/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11_2o5rv/supermercado/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-egi_9q60
         cwd: /tmp/pip-install-11_2o5rv/supermercado/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-11_2o5rv/supermercado/setup.py", line 7, in <module>
        with codecs_open('README.md', encoding='utf-8') as f:
      File "/var/lang/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by vincentsarago** [comment]
ahh I didn't realized there was a version `0.2.0` (need to add github tag and maybe pypi tag ;-)). I'm going to try with the newer version!

**Comment by vincentsarago** [comment]
closed in https://github.com/mapbox/supermercado/pull/36 🤦
